"""Add Employee

Revision ID: 213eba0eb580
Revises: f30e49302ba5
Create Date: 2023-06-08 00:55:19.179263

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '213eba0eb580'
down_revision = 'f30e49302ba5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employee',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ФИО', sa.String(), nullable=True),
    sa.Column('Обязанность', sa.String(), nullable=True),
    sa.Column('Квалификация', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_employee_id'), 'employee', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_employee_id'), table_name='employee')
    op.drop_table('employee')
    # ### end Alembic commands ###
