"""Add Stage

Revision ID: 4a3d4f51f313
Revises: c20d020c66c6
Create Date: 2023-06-07 23:36:16.543460

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a3d4f51f313'
down_revision = 'c20d020c66c6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Название', sa.String(), nullable=True),
    sa.Column('Направление', sa.String(), nullable=True),
    sa.Column('Дата_начала', sa.Date(), nullable=True),
    sa.Column('Дата_сдачи', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_id'), 'project', ['id'], unique=False)
    op.create_table('stage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_project', sa.Integer(), nullable=False),
    sa.Column('Название', sa.String(), nullable=True),
    sa.Column('Дата_начала', sa.Date(), nullable=True),
    sa.Column('Дата_сдачи', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['id_project'], ['project.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stage_id'), 'stage', ['id'], unique=False)
    op.drop_index('ix_Проект_id', table_name='Проект')
    op.drop_table('Проект')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Проект',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"Проект_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('Название', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('Направление', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('Дата_начала', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('Дата_сдачи', sa.DATE(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='Проект_pkey')
    )
    op.create_index('ix_Проект_id', 'Проект', ['id'], unique=False)
    op.drop_index(op.f('ix_stage_id'), table_name='stage')
    op.drop_table('stage')
    op.drop_index(op.f('ix_project_id'), table_name='project')
    op.drop_table('project')
    # ### end Alembic commands ###
