"""Add many tables

Revision ID: 5557ac37a314
Revises: 213eba0eb580
Create Date: 2023-06-08 01:25:14.295680

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5557ac37a314'
down_revision = '213eba0eb580'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('operation_phase',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_operation', sa.Integer(), nullable=False),
    sa.Column('id_phase', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_operation'], ['operation.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_phase'], ['phase.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_operation_phase_id'), 'operation_phase', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_operation_phase_id'), table_name='operation_phase')
    op.drop_table('operation_phase')
    # ### end Alembic commands ###
