"""Add Phase

Revision ID: 74c3030c0b1d
Revises: 4a3d4f51f313
Create Date: 2023-06-08 00:14:58.163966

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74c3030c0b1d'
down_revision = '4a3d4f51f313'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('phase',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_stage', sa.Integer(), nullable=False),
    sa.Column('Название', sa.String(), nullable=True),
    sa.Column('Дата_начала', sa.Date(), nullable=True),
    sa.Column('Дата_сдачи', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['id_stage'], ['stage.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_phase_id'), 'phase', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_phase_id'), table_name='phase')
    op.drop_table('phase')
    # ### end Alembic commands ###
