"""Add many tables3

Revision ID: 8913e90e88fc
Revises: d15b4cc6776a
Create Date: 2023-06-08 01:33:11.892673

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8913e90e88fc'
down_revision = 'd15b4cc6776a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employeegroup_operationphase',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_employee_group', sa.Integer(), nullable=False),
    sa.Column('id_operation_phase', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_employee_group'], ['employee_group.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_operation_phase'], ['operation_phase.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_employeegroup_operationphase_id'), 'employeegroup_operationphase', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_employeegroup_operationphase_id'), table_name='employeegroup_operationphase')
    op.drop_table('employeegroup_operationphase')
    # ### end Alembic commands ###
