"""Add many tables4

Revision ID: 8ded5556f225
Revises: 8913e90e88fc
Create Date: 2023-06-08 01:35:02.721845

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ded5556f225'
down_revision = '8913e90e88fc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employee_operation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_operation', sa.Integer(), nullable=False),
    sa.Column('id_employee', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_employee'], ['employee.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_operation'], ['operation.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_employee_operation_id'), 'employee_operation', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_employee_operation_id'), table_name='employee_operation')
    op.drop_table('employee_operation')
    # ### end Alembic commands ###
