"""Add many tables5

Revision ID: afd1d48f27f6
Revises: 8ded5556f225
Create Date: 2023-06-08 01:35:26.711798

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'afd1d48f27f6'
down_revision = '8ded5556f225'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
