"""Add many tables1

Revision ID: b7c8b3708506
Revises: 5557ac37a314
Create Date: 2023-06-08 01:27:27.505512

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b7c8b3708506'
down_revision = '5557ac37a314'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('group_phase',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_group', sa.Integer(), nullable=False),
    sa.Column('id_phase', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_group'], ['group.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_phase'], ['phase.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_group_phase_id'), 'group_phase', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_group_phase_id'), table_name='group_phase')
    op.drop_table('group_phase')
    # ### end Alembic commands ###
