"""Init

Revision ID: c20d020c66c6
Revises: 
Create Date: 2023-06-07 20:38:15.396093

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c20d020c66c6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Проект',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Название', sa.String(), nullable=True),
    sa.Column('Направление', sa.String(), nullable=True),
    sa.Column('Дата_начала', sa.Date(), nullable=True),
    sa.Column('Дата_сдачи', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Проект_id'), 'Проект', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Проект_id'), table_name='Проект')
    op.drop_table('Проект')
    # ### end Alembic commands ###
