"""Add many tables1

Revision ID: d15b4cc6776a
Revises: b7c8b3708506
Create Date: 2023-06-08 01:29:40.932436

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd15b4cc6776a'
down_revision = 'b7c8b3708506'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employee_group',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_group', sa.Integer(), nullable=False),
    sa.Column('id_employee', sa.Integer(), nullable=False),
    sa.Column('Дата вступления в группу', sa.Date(), nullable=True),
    sa.Column('Дата исключения из группы', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['id_employee'], ['employee.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_group'], ['group.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_employee_group_id'), 'employee_group', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_employee_group_id'), table_name='employee_group')
    op.drop_table('employee_group')
    # ### end Alembic commands ###
