"""Add Group

Revision ID: f30e49302ba5
Revises: 048ac2c9f49e
Create Date: 2023-06-08 00:47:02.880195

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f30e49302ba5'
down_revision = '048ac2c9f49e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('group',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Название', sa.String(), nullable=True),
    sa.Column('Кол-во людей', sa.Integer(), nullable=True),
    sa.Column('Функциональный список', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_group_id'), 'group', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_group_id'), table_name='group')
    op.drop_table('group')
    # ### end Alembic commands ###
